#!/usr/bin/env python3
# -*- coding: utf-8 -*-

ACTIVE_CONFIGURATION_SETTING_NAME = "activeConfiguration"
REMAP_KEYS_SETTING_NAME = "remapKeys"
IN_PROCESS_REMAP_KEYS_SETTING_NAME = "inProcess"
REMAP_SHORTCUTS_SETTING_NAME = "remapShortcuts"
GLOBAL_REMAP_SHORTCUTS_SETTING_NAME = "global"
APP_SPECIFIC_REMAP_SHORTCUTS_SETTING_NAME = "appSpecific"
ORIGINAL_KEYS_SETTING_NAME = "originalKeys"
NEW_REMAP_KEYS_SETTING_NAME = "newRemapKeys"
TARGET_APP_SETTING_NAME = "targetApp"